services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

    